from sqlalchemy import Column, Integer, String, Text, DateTime, JSON
from sqlalchemy.sql import func

from .database import Base


class Idea(Base):
    """
    A single startup idea submitted to (or generated by) IdeaForge, together
    with the validation analysis computed for it.
    """

    __tablename__ = "ideas"

    id = Column(Integer, primary_key=True, index=True)

    author = Column(String(120), nullable=False, default="Anonymous")
    title = Column(String(200), nullable=False)
    description = Column(Text, nullable=False)
    category = Column(String(60), nullable=False, default="Tech")
    tags = Column(JSON, nullable=False, default=list)

    votes = Column(Integer, nullable=False, default=1)
    comments = Column(Integer, nullable=False, default=0)

    # "user" for ideas submitted through the form, "ai_generated" for ones
    # produced by the "Generate AI Idea" button.
    source = Column(String(20), nullable=False, default="user")

    # --- Validation analysis (computed by app.services.orchestrator) -----
    validation_score = Column(Integer, nullable=False, default=0)
    market_category = Column(String(120), nullable=False, default="")
    similar_startups = Column(JSON, nullable=False, default=list)
    competitors = Column(JSON, nullable=False, default=list)
    suggested_improvements = Column(JSON, nullable=False, default=list)
    differentiation_opportunities = Column(JSON, nullable=False, default=list)
    market_gaps = Column(JSON, nullable=False, default=list)

    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
